- name: install and start mysql
  hosts: web
  become: yes

  tasks:

    - name: install mysql server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes



