- name: install and start mysql (mariadb)
  hosts: web
  become: yes

  tasks:

    - name: install mariadb server
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    - name: start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes